name: Builds


on:
  workflow_dispatch:
    inputs:
      title:
        description: "Workflow Title:"
        default: Yet Another Android Build

jobs:
  build:
    runs-on: ubuntu-latest
    title: ${{ github.event.inputs.title }}

    steps:
      - uses: actions/checkout@v2
      - name: "Starting Build..."
        uses: GoldenspearLLC/build-jenkins-job@master
        with:
          jenkins-url: ${{ secrets.JENKINS_URL }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          user: "ayokaacr"
          job-path: "/home/build/line/releases-1/"
          job-params: 

      - name: Current Build Status
        run: echo "${{ steps.job-build.outputs.job_status }}"
