name: Cedric Builds


on:
  workflow_dispatch:

jobs:
  ppui-A11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Starting Build..."
        uses: GoldenspearLLC/build-jenkins-job@master
        with:
          jenkins-url: ${{ secrets.JENKINS_URL }}
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          user: "ayokaacr"
          job-path: "/home/build/"
          job-params: 

      - name: Current Build Status
        run: echo "${{ steps.job-build.outputs.job_status }}"
